// <auto-generated />
namespace $safeprojectname$.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class createdb1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdb1));
        
        string IMigrationMetadata.Id
        {
            get { return "201911150759399_createdb1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
